/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MunicipiosIndexRouteImport } from './routes/municipios.index'
import { Route as BairrosIndexRouteImport } from './routes/bairros.index'
import { Route as MunicipiosMunicipalityIdRouteImport } from './routes/municipios.$municipalityId'

const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipiosIndexRoute = MunicipiosIndexRouteImport.update({
  id: '/municipios/',
  path: '/municipios/',
  getParentRoute: () => rootRouteImport,
} as any)
const BairrosIndexRoute = BairrosIndexRouteImport.update({
  id: '/bairros/',
  path: '/bairros/',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipiosMunicipalityIdRoute =
  MunicipiosMunicipalityIdRouteImport.update({
    id: '/municipios/$municipalityId',
    path: '/municipios/$municipalityId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/municipios/$municipalityId': typeof MunicipiosMunicipalityIdRoute
  '/bairros/': typeof BairrosIndexRoute
  '/municipios/': typeof MunicipiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/municipios/$municipalityId': typeof MunicipiosMunicipalityIdRoute
  '/bairros': typeof BairrosIndexRoute
  '/municipios': typeof MunicipiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/municipios/$municipalityId': typeof MunicipiosMunicipalityIdRoute
  '/bairros/': typeof BairrosIndexRoute
  '/municipios/': typeof MunicipiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mapa'
    | '/municipios/$municipalityId'
    | '/bairros/'
    | '/municipios/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mapa' | '/municipios/$municipalityId' | '/bairros' | '/municipios'
  id:
    | '__root__'
    | '/'
    | '/mapa'
    | '/municipios/$municipalityId'
    | '/bairros/'
    | '/municipios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapaRoute: typeof MapaRoute
  MunicipiosMunicipalityIdRoute: typeof MunicipiosMunicipalityIdRoute
  BairrosIndexRoute: typeof BairrosIndexRoute
  MunicipiosIndexRoute: typeof MunicipiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipios/': {
      id: '/municipios/'
      path: '/municipios'
      fullPath: '/municipios/'
      preLoaderRoute: typeof MunicipiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bairros/': {
      id: '/bairros/'
      path: '/bairros'
      fullPath: '/bairros/'
      preLoaderRoute: typeof BairrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipios/$municipalityId': {
      id: '/municipios/$municipalityId'
      path: '/municipios/$municipalityId'
      fullPath: '/municipios/$municipalityId'
      preLoaderRoute: typeof MunicipiosMunicipalityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapaRoute: MapaRoute,
  MunicipiosMunicipalityIdRoute: MunicipiosMunicipalityIdRoute,
  BairrosIndexRoute: BairrosIndexRoute,
  MunicipiosIndexRoute: MunicipiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
